// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate environment variables with fallback for production
// TODO: Configurare queste variabili su Vercel
const SUPABASE_URL_FINAL = SUPABASE_URL || 'https://zflhbbftpasyfqusoibs.supabase.co';
const SUPABASE_PUBLISHABLE_KEY_FINAL = SUPABASE_PUBLISHABLE_KEY || '';

if (!SUPABASE_URL && import.meta.env.PROD) {
  console.warn('⚠️ VITE_SUPABASE_URL non configurata, usando fallback. Configura su Vercel!');
}

if (!SUPABASE_PUBLISHABLE_KEY && import.meta.env.PROD) {
  console.warn('⚠️ VITE_SUPABASE_PUBLISHABLE_KEY non configurata. Configura su Vercel!');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL_FINAL, SUPABASE_PUBLISHABLE_KEY_FINAL, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});